export const UPDATE_MENU_CONFIG = "UPDATE_MENU_CONFIG";
export const OPEN_FORM_TYPE = "OPEN_FORM_TYPE";
export const UPDATE_APP_CONFIG = "UPDATE_APP_CONFIG";
export const UPDATE_REG_CONFIG = "UPDATE_REG_CONFIG";
export const UPDATE_GAME_LIST = "UPDATE_GAME_LIST";
export const UPDATE_APP_LABLES_CONFIG = "UPDATE_APP_LABLES_CONFIG";
export const UPDATE_USER_LOGIN = "UPDATE_USER_LOGIN";
export const UPDATE_MENU_LIST = "UPDATE_MENU_LIST";
export const UPDATE_PROVIDERS_LIST = "UPDATE_PROVIDERS_LIST";
export const UPDATE_CMS_PLAIN_MENU_LIST = "UPDATE_CMS_PLAIN_MENU_LIST";
export const OPEN_MODEL_WINDOW = "OPEN_MODEL_WINDOW";
export const CLOSE_MODEL_WINDOW = "CLOSE_MODEL_WINDOW";
export const OPEN_GAME_WINDOW = "OPEN_GAME_WINDOW";
export const UPDATE_DEVICE_TYPE_OBJ = "UPDATE_DEVICE_TYPE_OBJ";
export const PLAYER_INFO = "PLAYER_INFO";
export const GAME_SECTIONS = "GAME_SECTIONS";


